# Generated by Django 4.0.1 on 2022-01-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_alter_stock_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('ticker', models.CharField(max_length=5)),
                ('price', models.FloatField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
