# Generated by Django 4.0.1 on 2022-01-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_stocks_delete_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountholder',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='accountholder',
            name='available_cash',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='accountholder',
            name='portfolio',
            field=models.ManyToManyField(to='App1.Stocks'),
        ),
    ]
