# Generated by Django 4.0.1 on 2022-01-21 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_remove_accountholder_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountholder',
            name='portfolio',
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='available_cash',
            field=models.FloatField(default=1000000),
        ),
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.FloatField(default=0.0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.stocks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.accountholder')),
            ],
        ),
    ]
