# Generated by Django 4.0.1 on 2022-01-22 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_remove_accountholder_portfolio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holdings',
            old_name='user',
            new_name='userid',
        ),
    ]
